export const TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTUyM2RkZjQxYmVlNjAwMjExNDRmNjciLCJpYXQiOjE2MzI3Nzk3NDN9.oUo_RNR3Geu4oRX8JLCdMWTpcyxjwM_hLw_vzGrMYSQ'
export const PRODUCTS_API = 'https://coding-challenge-api.aerolab.co/products'
export const REDEEM_API = 'https://coding-challenge-api.aerolab.co/redeem'
export const USER_API = 'https://coding-challenge-api.aerolab.co/user/me'
export const USER_HISTORY_API = 'https://coding-challenge-api.aerolab.co/user/history'
export const USER_POINTS_API = 'https://coding-challenge-api.aerolab.co/user/points'